services:
  realtime_humble:
    image: bimanual:franka
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: realtime_humble
    tty: true
    environment:
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
    network_mode: host
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
